
REDSTONE_BLOCK = 152
SNOW_BLOCK = 78
EMPTY_BLOCK = 0

# A block which represents the "true" value.
TRUE_BLOCK = REDSTONE_BLOCK
# A block which represents the "false" value.
FALSE_BLOCK = SNOW_BLOCK

IMPULSE_COMMAND_BLOCK = 137
REPEATING_COMMAND_BLOCK = 210
CHAIN_COMMAND_BLOCK = 211
